import type { ThemePreset } from "@/themes/types";

export const cyberpunkTheme: ThemePreset = {
  id: "cyberpunk",
  label: "Cyberpunk",
  description: "Blackout shell with polished neon cyan, acid yellow, magenta, and electric green accents.",
  source: "core",
  mode: "dark",
  tightness: "tight",
  surfaceHierarchy: "soft",
  tokens: {
    background: "#020204",
    foreground: "#C7F7FF",
    card: "#09070F",
    "card-foreground": "#C7F7FF",
    popover: "#0C0812",
    "popover-foreground": "#F6F2A5",
    sidebar: "#07060B",
    "sidebar-foreground": "#F09BFF",
    topbar: "#06050A",
    "topbar-foreground": "#F5F0B0",
    muted: "#14101C",
    "muted-foreground": "#B694D3",
    border: "#302445",
    input: "#120D19",
    primary: "#F3EE72",
    "primary-foreground": "#141000",
    secondary: "#19132A",
    "secondary-foreground": "#F4C7FF",
    accent: "#FF5AD9",
    "accent-foreground": "#190417",
    danger: "#FF5B84",
    "danger-foreground": "#24020C",
    success: "#5BFF9D",
    "success-foreground": "#03150B",
    warning: "#FFB347",
    "warning-foreground": "#2A1200",
    positive: "#5BFF9D",
    negative: "#FF5B84",
    ring: "#38E8FF",
    "chart-grid": "#2AA8C9",
    radius: "16px",
  },
};
