import type { ThemePreset } from "@/themes/types";

export const mainSequenceSpaceTheme: ThemePreset = {
  id: "main-sequence-space",
  label: "Main Sequence Space",
  description: "Deep-space Main Sequence variant with stellar white glare and blue gravity glow.",
  source: "core",
  mode: "dark",
  tightness: "tight",
  surfaceHierarchy: "soft",
  tokens: {
    background: "#020409",
    foreground: "#F8FBFF",
    card: "#080C14",
    "card-foreground": "#F8FBFF",
    popover: "#0A0F18",
    "popover-foreground": "#F8FBFF",
    sidebar: "#04070D",
    "sidebar-foreground": "#D8E2F1",
    topbar: "#050913",
    "topbar-foreground": "#FFFFFF",
    muted: "#0F1520",
    "muted-foreground": "#93A3BC",
    border: "#101723",
    input: "#0E1520",
    primary: "#F8FBFF",
    "primary-foreground": "#03060C",
    secondary: "#121A29",
    "secondary-foreground": "#EAF2FF",
    accent: "#5FB4FF",
    "accent-foreground": "#03101B",
    danger: "#FF67B3",
    "danger-foreground": "#1C0310",
    success: "#61C8FF",
    "success-foreground": "#03131D",
    warning: "#E8A23C",
    "warning-foreground": "#241200",
    positive: "#61C8FF",
    negative: "#FF67B3",
    ring: "#7DD3FC",
    "chart-grid": "#DCEBFF",
    radius: "16px",
  },
};
